[project]
name = "pipeline-py"
version = "0.1.0"
description = ""
authors = [
    {name = "Timothy Clarke"}
]
requires-python = ">=3.14"
dependencies = [
    "ruff (>=0.15.20,<0.16.0)",
    "hdrhistogram (>=0.10.7,<0.11.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
