[rgb_queue_config]
name = "RGB"
fps = 30
capacity_frames = 3

[rgb_policy]
type = "AdaptiveDecimation"
threshold = 2
min_ratio = 2
max_ratio = 10

[accel_queue_config]
name = "Accelerometer"
fps = 1600
capacity_frames = 160

[accel_policy]
type = "AdaptiveDecimation"
threshold = 128 # 80% of capacity_frames
min_ratio = 2
max_ratio = 10

[gyro_queue_config]
name = "Gyroscope"
fps = 2000
capacity_frames = 200

[gyro_policy]
type = "AdaptiveDecimation"
threshold = 160 # 80% of capacity_frames
min_ratio = 2
max_ratio = 10
