#pragma once
#include <atomic>
#include <cstdint>
#include <string>
#include <string_view>

/// Connects to a circular shared memory buffer and reads its frames.
class ShmBuffer
{
private:
  /// \brief Represents the header of the shared memory buffer.
  ///
  /// Aligned to 64 bytes to ensure proper memory alignment for atomic
  /// operations.
  struct alignas(64) Header
  {
    /// The magic number used to identify the shared memory buffer. It is set to
    /// the ASCII representation of "EDGE" (0x45444745) to help confirm that the
    /// buffer has been correctly initialised and is valid.
    static constexpr uint32_t MAGIC = 0x45444745;

    /// The version of the shared memory buffer. It is set to 1 for the initial
    /// version. This field allows for backward compatibility in the future.
    static constexpr uint32_t VERSION = 1;

    /// A magic number used to identify the shared memory buffer.
    uint32_t magic;

    /// The version of the shared memory buffer.
    uint32_t version;

    /// The size of each frame in bytes.
    uint32_t frame_size_bytes;

    /// The total number of frames that the buffer can hold before wrapping
    /// around.
    uint32_t capacity_frames;

    /// The sequence number of the last written frame. This field is used to
    /// signal to consumers that a new frame has been written and is ready for
    /// processing.
    std::atomic<uint64_t> seq_num;
  };

public:
  /// The stream ID for the RGB camera frames.
  static constexpr size_t RGB_STREAM_ID = 0;

  /// The stream ID for the accelerometer frames.
  static constexpr size_t ACCEL_STREAM_ID = 1;

  /// The stream ID for the gyroscope frames.
  static constexpr size_t GYRO_STREAM_ID = 2;

  /// The total number of streams supported by the shared memory buffer.
  static constexpr size_t NUM_STREAMS = GYRO_STREAM_ID + 1;

  /// The index of when the frame was generated by the producer and pushed to
  /// the unbounded buffer.
  static constexpr size_t GENERATED_TS = 0;

  /// The index of when the frame was bridged from the unbounded buffer to the
  /// idiomatic buffer.
  static constexpr size_t BRIDGED_TS = 1;

  /// The index of when the frame was pulled from the idiomatic buffer by the
  /// pipeline for processing.
  static constexpr size_t PIPELINE_IN_TS = 2;

  /// The index of when the frame was pushed to the ONNX Runtime for inference.
  static constexpr size_t PIPELINE_OUT_TS = 3;

  /// The index of when late fusion began.
  static constexpr size_t FUSION_IN_TS = 4;

  /// The index of when late fusion completed.
  static constexpr size_t FUSION_OUT_TS = 5;

  /// The total number of timestamps associated with each frame.
  static constexpr size_t NUM_TIMESTAMPS = FUSION_OUT_TS + 1;

  /// Represents a single frame read from the shared memory buffer.
  struct Frame
  {
    /// The stream ID associated with this frame. Used to identify the source of
    /// the frame.
    size_t stream_id;

    /// The sequence number of the frame.
    uint64_t seq_num = 0;

    /// The six timestamps associated with the frame, in nanoseconds:
    /// * GENERATED: when the generator pushes to the unbounded buffer
    /// * BRIDGED: when the bridge pushes to the idiomatic buffer
    /// * PIPELINE_IN: when the pipeline pulls the event from the idiomatic
    ///   buffer
    /// * PIPELINE_OUT: when the pipeline pushes data to the ONNX Runtime for
    ///   inference
    /// * FUSION_IN: when inference completes and the pipeline begins late
    ///   fusion
    /// * FUSION_OUT: when late fusion completes and the pipeline produces the
    ///   final output
    uint64_t timestamps[6];
  };

public:
  /// \brief Constructs a new ShmBuffer instance and connects to the shared
  /// memory buffer with the specified name.
  ///
  /// The buffer must have been created by a producer process and must contain a
  /// valid ShmHeader at the start of the buffer. If the buffer does not exist
  /// or is invalid, an exception is thrown.
  ///
  /// \param name The name of the shared memory buffer to connect to.
  /// \param stream_id The stream ID associated with this buffer. Used to create
  /// the `ShmFrame` struct when reading frames.
  ShmBuffer(const std::string_view& name, const size_t stream_id);

  /// \brief Spin-wait until the next frame is available, returning a slice to
  /// the new frame's bytes.
  ///
  /// Sleeping or blocking, using futexes, is not used to avoid OS-level context
  /// switches, which would introduce latency variance as the thread is
  /// descheduled and rescheduled again. This must not happen as it will
  /// confound the latency measurements, especially for the 2,000 Hz gyroscope
  /// data.
  ///
  /// By spin-waiting, the thread is never yielded to the OS, and the CPU
  /// remains in a high-performance state. Note that this does come at the cost
  /// of higher power consumption.
  ///
  /// \return An ShmFrame with the sequence number and creation time of the next
  /// frame.
  Frame next_frame();

private:
  /// \brief Opens the shared memory file with the given name and returns a
  /// pointer to the start of the shared memory region.
  ///
  /// The shared memory file must have been created by a producer process and
  /// must contain a valid `ShmHeader` at the start of the buffer.
  ///
  /// \param name The name of the shared memory file to open.
  /// \return A pointer to the start of the shared memory region.
  Header* open_shm_file();

private:
  /// The name of the shared memory buffer. Also used for logging and error
  /// messages.
  const std::string name_;

  /// The stream ID associated with this buffer. Used to create the `ShmFrame`
  /// struct when reading frames.
  const size_t stream_id_;

  /// A pointer to the header of the shared memory buffer.
  Header* header_;

  /// A pointer to the data section of the shared memory buffer.
  char* data_ptr_;

  /// The index of the next frame to read from the buffer. This is used to track
  /// the consumer's position in the circular buffer and to detect when the
  /// producer has lapped the consumer.
  uint64_t frame_idx_ = 0;

  /// The total number of frames that the buffer can hold before wrapping
  /// around. This is duplicated from the header for performance reasons, as it
  /// avoids dereferencing the header pointer when the producer laps the
  /// consumer.
  uint64_t capacity_frames_;

  /// The size of each frame in bytes. This is duplicated from the header for
  /// performance reasons, as it avoids dereferencing the header pointer on
  /// every frame read.
  size_t frame_size_bytes_;
};
