import ctypes
import struct
import time
from multiprocessing import shared_memory
from multiprocessing.resource_tracker import unregister


class ShmHeader(ctypes.Structure):
    """Represents the header of the shared memory buffer. Aligned to 64
    bytes."""

    _pack_ = 1

    # fmt: off
    _fields_ = [
        # A magic number used to identify the shared memory buffer.
        ('magic', ctypes.c_uint32),

        # The version of the shared memory buffer.
        ('version', ctypes.c_uint32),

        # The size of each frame in bytes.
        ('frame_size_bytes', ctypes.c_uint32),

        # The total number of frames that the buffer can hold before wrapping
        # around.
        ('capacity_frames', ctypes.c_uint32),

        # The sequence number of the last written frame. This field is used to
        # signal to consumers that a new frame has been written and is ready for
        # processing.
        ('seq_num', ctypes.c_uint64),

        # The pipeline stage of the shared memory buffer. This field is used to
        # synchronise between the generator and the pipeline. Initialised to
        # zero, it is incremented to one when the pipeline is ready to receive
        # data, and incremented to two when the generator has finished writing
        # data.
        ('pipeline_stage', ctypes.c_uint64),

        # Pad the structure to 64 bytes.
        ('_padding', ctypes.c_uint8 * 32),
    ]
    # fmt: on


class ShmFrame:
    """Represents a single frame read from the shared memory buffer."""

    # Using __slots__ instead of the default __dict__ reduces memory usage and
    # improces attribute access speed.
    __slots__ = ['stream_id', 'seq_num', 'timestamps']

    def __init__(self, stream_id: int, seq_num: int, timestamps: list[int]):
        """Constructs a new ShmBuffer instance and connects to the shared memory
        buffer with the specified name.

        The buffer must have been created by a producer process and must contain
        a valid ShmHeader at the start of the buffer. If the buffer does not
        exist or is invalid, an exception is thrown.

        Args:
            stream_id: the stream ID associated with this frame. Used to
            identify the source of the frame.
            seq_num: the sequence number of the frame.
            timestamps: the six timestamps associated with the frame, in
            nanoseconds:
            * GENERATED: when the generator pushes to the unbounded buffer
            * BRIDGED: when the bridge pushes to the idiomatic buffer
            * PIPELINE_IN: when the pipeline pulls the event from the idiomatic
              buffer
            * PIPELINE_OUT: when the pipeline pushes data to the ONNX Runtime
              for inference
            * FUSION_IN: when inference completes and the pipeline begins late
              fusion
            * FUSION_OUT: when late fusion completes and the pipeline produces
              the final output
        """
        self.stream_id = stream_id
        self.seq_num = seq_num
        self.timestamps = timestamps


class ShmBuffer:
    """Connects to a circular shared memory buffer and reads its frames."""

    RGB_STREAM_ID = 0
    """The stream ID for the RGB camera frames."""

    ACCEL_STREAM_ID = 1
    """The stream ID for the accelerometer frames."""

    GYRO_STREAM_ID = 2
    """The stream ID for the gyroscope frames."""

    NUM_STREAMS = 3
    """The total number of streams supported by the shared memory buffer."""

    GENERATED_TS = 0
    """The index of when the frame was generated by the producer and pushed to
    the unbounded buffer."""

    BRIDGED_TS = 1
    """The index of when the frame was bridged from the unbounded buffer to the
    idiomatic buffer."""

    PIPELINE_IN_TS = 2
    """The index of when the frame was pulled from the idiomatic buffer by the
    pipeline for processing."""

    PIPELINE_OUT_TS = 3
    """The index of when the frame was pushed to the ONNX Runtime for
    inference."""

    FUSION_IN_TS = 4
    """The index of when late fusion began."""

    FUSION_OUT_TS = 5
    """The index of when late fusion completed."""

    NUM_TIMESTAMPS = 6
    """The total number of timestamps associated with each frame."""

    MAGIC = 0x45444745
    """The magic number used to identify the shared memory buffer. It is set to
    the ASCII representation of "EDGE" (0x45444745) to help confirm that the
    buffer has been correctly initialised and is valid."""

    VERSION = 1
    """The version of the shared memory buffer. It is set to 1 for the initial
    version. This field allows for backward compatibility in the future."""

    WAITING = 0
    """The generator is waiting for the pipeline to be ready to receive data."""

    READY = 1
    """The pipeline is ready to receive data from the generator."""

    FINISHED = 2
    """The generator has finished writing data to the shared memory buffer."""

    POISON_PILL = (1 << 64) - 1
    """The sequence number used to signal to the consumer that the producer has
    finished writing data and that no more frames will be produced. This value
    is set to the maximum value of a 64-bit unsigned integer (UINT64_MAX)."""

    def __init__(self, name: str, stream_id: int):
        """Constructs a new ShmBuffer instance and connects to the shared memory
        buffer with the specified name.

        The buffer must have been created by a producer process and must contain
        a valid ShmHeader at the start of the buffer. If the buffer does not
        exist or is invalid, an exception is thrown.

        Args:
            name: The name of the shared memory buffer to connect to.
            stream_id: The stream ID associated with this buffer. Used to create
            the `ShmFrame` struct when reading frames.
        """
        self.name = name
        self.stream_id = stream_id

        try:
            self.shm_ptr = shared_memory.SharedMemory(name=name)
            unregister(self.shm_ptr._name, 'shared_memory')
        except FileNotFoundError:
            raise RuntimeError(f"Failed to open shared memory '{name}'.")

        self.header = ShmHeader.from_buffer(self.shm_ptr.buf)

        if self.header.magic != self.MAGIC:
            raise RuntimeError(
                f"Memory corruption or invalid magic "
                "number in shared memory '{name}'"
            )
        if self.header.version != self.VERSION:
            raise RuntimeError(
                f"Incompatible version in shared memory "
                f"'{name}': expected {self.VERSION}, "
                f"got {self.header.version}"
            )

        self.data_offset = ctypes.sizeof(ShmHeader)
        self.frame_idx = 0
        self.capacity_frames = self.header.capacity_frames
        self.frame_size_bytes = self.header.frame_size_bytes

        self.header.pipeline_stage = self.READY

    def close(self):
        """Closes the shared memory buffer."""
        self.header = None
        self.shm_ptr.close()

    def next_frame(self) -> ShmFrame:
        """Loop until the next frame is available, and return it.

        Sleeping or blocking, using futexes, is not used to avoid OS-level
        context switches, which would introduce latency variance as the thread
        is descheduled and rescheduled again. This must not happen as it will
        confound the latency measurements, especially for the 2,000 Hz gyroscope
        data.

        By spin-waiting, the thread is never yielded to the OS, and the CPU
        remains in a high-performance state. Note that this does come at the
        cost of higher power consumption.

        Returns:
            An ShmFrame with the sequence number and creation time of the next
            frame.
        """

        while True:
            # The producer increments the sequence number after writing a frame,
            # using Release ordering to ensure all previous writes have been
            # flushed. Python does not provide a way to perform an atomic
            # acquire, and so there is a risk that the consumer may read a stale
            # value of the sequence number.
            seq_num = self.header.seq_num

            if seq_num > self.frame_idx:
                if seq_num - self.frame_idx > self.capacity_frames:
                    # The producer has lapped the consumer, which means that
                    # frames have been overwritten before they could be read.
                    # Print a warning to stderr and jump ahead to the oldest
                    # surviving frame. For example, if the producer is at
                    # sequence 35 and the capacity is 30, the oldest surviving
                    # frame is at sequence 6.
                    print(
                        f"[WARNING] {self.name} producer lapped "
                        f"consumer by {seq_num - self.frame_idx} frames."
                    )
                    self.frame_idx = seq_num - self.capacity_frames

                circular_idx = self.frame_idx % self.capacity_frames
                data_offset = self.data_offset + (
                    circular_idx * self.frame_size_bytes
                )

                t_bridged = time.perf_counter_ns()

                # Extract the 8-byte generated timestamp (little endian)
                t_generated = struct.unpack_from(
                    '<Q', self.shm_ptr.buf, data_offset
                )[0]

                self.frame_idx += 1

                return ShmFrame(
                    self.stream_id,
                    self.frame_idx + 1,
                    [t_generated, t_bridged, 0, 0, 0, 0],
                )

            if self.header.pipeline_stage == self.FINISHED:
                return ShmFrame(self.stream_id, self.POISON_PILL, [0] * 6)

            # Avoid latency variance that would be introduced if the OS
            # scheduler were used by sleeping or blocking.
            pass
